server:
  port: 8081

spring:
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  base-url: ${APP_BASE_URL}
  frontend-url: ${FRONTEND_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: WARN
    com.mdevs.shortenly: WARN
